name: ${project.parent.name}
description: ${project.parent.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.epicanchors.EpicAnchors
softdepend:
  - Holograms
  - HolographicDisplays
  - Vault

author: Craftaro
authors: [ SpraxDev ]
website: ${project.parent.url}

commands:
  EpicAnchors:
    aliases:
      - ea

permissions:
  EpicAnchors.cmd.show:
    default: true

  EpicAnchors.admin:
    children:
      EpicAnchors.cmd.reload: true
      EpicAnchors.cmd.settings: true
      EpicAnchors.cmd.give: true
